site_name: Kirsch Recipes
theme:
  name: material
  favicon: images/favicon_io/favicon.ico
  logo: images/favicon_io/icon.png
  palette:
    primary: blue grey
plugins:
  - glightbox
  - macros
  - search
  - blog:
      blog_dir: recipes
      post_readtime: false
      archive: false
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
nav:
  - index.md
  - Recipes:
    - recipes/index.md 
