name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    container:
      image: python:3
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
      
      - name: Git
        run: |
          git config --global user.name 'git-actions'
          git config --global user.email 'samkirsch10@users.noreply.github.com'
          git config --global --add safe.directory /__w/recipes/recipes

      - name: Build docs
        run: |
          ls -la
          pip install -r requirements.txt
          for recipe in $(ls docs/recipes/posts); do
            name=$(echo $recipe | sed 's/.md//' | sed 's/_/ /g')
            echo "[$name](recipes/posts/$recipe)  " >> docs/index.md
          done
          mkdir -p dist
          cp CNAME dist
          mkdocs gh-deploy -d dist/ --dirty --force