name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    container:
      image: python:3
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Build docs
        run: |
          ls -la
          pip install -r requirements.txt
          mkdocs gh-deploy